blank_issues_enabled: false
contact_links:
  - name: Having problems with HalfmoonUI?
    url: https://github.com/halfmoonui/halfmoon/issues
    about: If you have problems, please report them on the official halfmoonUI issue tracker.
